name: Upload Notebook to Notion

on:
  push:
    branches:
      - main
    paths:
      - '**.ipynb'  # Trigger on Jupyter notebook changes
  workflow_dispatch:  # Allow manual triggering

jobs:
  upload_to_notion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          pip install jupyter nbconvert requests

      - name: Convert notebook to Markdown
        run: |
          # Create the markdown output directory if it doesn't exist
          mkdir -p markdown
          # Convert the main notebook to markdown
          jupyter nbconvert --to markdown getImage_from_DSA.ipynb

      - name: Upload to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
        run: |
          python -c "
import os
import requests

def upload_to_notion(markdown_file):
    with open(markdown_file, 'r') as file:
        content = file.read()

    headers = {
        'Authorization': f'Bearer {os.environ['NOTION_TOKEN']}',
        'Content-Type': 'application/json',
    }

    data = {
        'parent': {'id': os.environ['NOTION_PAGE_ID']},
        'properties': {
            'title': [{'text': {'content': 'Your Page Title'}}]
        },
        'children': [
            {
                'object': 'block',
                'type': 'paragraph',
                'paragraph': {
                    'text': [{'type': 'text', 'text': {'content': content}}],
                },
            }
        ],
    }

    response = requests.post('https://api.notion.com/v1/pages', headers=headers, json=data)
    print(response.status_code)

upload_to_notion('markdown/getImage_from_DSA.md')
          "

